working in 2 tickets in this single branch
PIH/openmrs-config-pihemr pull request #447
Opened 2023-10-20 20:33 UTC by louidorjp

Ticket1: https://pihemr.atlassian.net/jira/software/c/projects/HAI/boards/156?selectedIssue=HAI-886
Ticket2: https://pihemr.atlassian.net/jira/software/c/projects/HAI/boards/156?selectedIssue=HAI-865

![if_other_service](https://github.com/PIH/openmrs-config-pihemr/assets/56307966/542d08f2-1e7e-400f-84a5-268667e75327)
![Screenshot from 2023-10-20 16-27-46](https://github.com/PIH/openmrs-config-pihemr/assets/56307966/7e670d96-2063-4deb-ad50-e0280d2856e1)

Please review this PR

2023-10-20 22:59 UTC, lnball requested changes
Please update with existing message properties.  Thanks.  Otherwise it looks good.

2023-10-20 22:59 UTC, lnball commented on configuration/messageproperties/messages_en.properties
> +pih.app.mental.health.other=Other
You don't need new messages when they exist.  Please re-use these:

- pihcore.other
- pihcore.location.ed
- pihcore.location.surgery
- pihcore.location.intMed

2023-10-21 03:36 UTC, louidorjp commented
@lnball existing message properties added

2023-10-23 13:52 UTC, merged

2023-10-23 13:53 UTC, lnball commented
Looks good @louidorjp .  Thanks.